// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RmsErp.Api.Data;

#nullable disable

namespace RmsErp.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260322234743_SistemaModulosDinamicos")]
    partial class SistemaModulosDinamicos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RmsErp.Api.Models.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactoPrincipal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("RmsErp.Api.Models.Modulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlugRaiz")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Modulos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icono = "M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6",
                            Nombre = "Panel de Control",
                            Orden = 1,
                            Ruta = "/panel",
                            SlugRaiz = "panel"
                        },
                        new
                        {
                            Id = 2,
                            Icono = "M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z M15 12a3 3 0 11-6 0 3 3 0 016 0z",
                            Nombre = "Administración",
                            Orden = 2,
                            Ruta = "/administracion",
                            SlugRaiz = "admin"
                        },
                        new
                        {
                            Id = 3,
                            Icono = "M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10",
                            Nombre = "Proyectos",
                            Orden = 3,
                            Ruta = "/proyectos",
                            SlugRaiz = "proyectos"
                        },
                        new
                        {
                            Id = 4,
                            Icono = "M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z",
                            Nombre = "Finanzas",
                            Orden = 4,
                            Ruta = "/finanzas",
                            SlugRaiz = "finanzas"
                        },
                        new
                        {
                            Id = 5,
                            Icono = "M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z",
                            Nombre = "Gestión Humana",
                            Orden = 5,
                            Ruta = "/gestion-humana",
                            SlugRaiz = "gestionhumana"
                        });
                });

            modelBuilder.Entity("RmsErp.Api.Models.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModuloId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Permisos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = "Administracion",
                            ModuloId = 2,
                            Nombre = "Ver Usuarios",
                            Slug = "admin.usuarios.leer"
                        },
                        new
                        {
                            Id = 2,
                            Area = "Administracion",
                            ModuloId = 2,
                            Nombre = "Crear Usuarios",
                            Slug = "admin.usuarios.crear"
                        },
                        new
                        {
                            Id = 3,
                            Area = "Administracion",
                            ModuloId = 2,
                            Nombre = "Editar Usuarios",
                            Slug = "admin.usuarios.editar"
                        },
                        new
                        {
                            Id = 4,
                            Area = "Administracion",
                            ModuloId = 2,
                            Nombre = "Eliminar Usuarios",
                            Slug = "admin.usuarios.borrar"
                        },
                        new
                        {
                            Id = 5,
                            Area = "Administracion",
                            ModuloId = 2,
                            Nombre = "Ver Clientes",
                            Slug = "admin.clientes.leer"
                        },
                        new
                        {
                            Id = 6,
                            Area = "Administracion",
                            ModuloId = 2,
                            Nombre = "Crear Clientes",
                            Slug = "admin.clientes.crear"
                        },
                        new
                        {
                            Id = 7,
                            Area = "Administracion",
                            ModuloId = 2,
                            Nombre = "Editar Clientes",
                            Slug = "admin.clientes.editar"
                        },
                        new
                        {
                            Id = 8,
                            Area = "Administracion",
                            ModuloId = 2,
                            Nombre = "Eliminar Clientes",
                            Slug = "admin.clientes.borrar"
                        },
                        new
                        {
                            Id = 9,
                            Area = "Administracion",
                            ModuloId = 2,
                            Nombre = "Ver Contratistas",
                            Slug = "admin.contratistas.leer"
                        },
                        new
                        {
                            Id = 10,
                            Area = "Administracion",
                            ModuloId = 2,
                            Nombre = "Crear Contratistas",
                            Slug = "admin.contratistas.crear"
                        },
                        new
                        {
                            Id = 11,
                            Area = "Administracion",
                            ModuloId = 2,
                            Nombre = "Editar Contratistas",
                            Slug = "admin.contratistas.editar"
                        },
                        new
                        {
                            Id = 12,
                            Area = "Administracion",
                            ModuloId = 2,
                            Nombre = "Eliminar Contratistas",
                            Slug = "admin.contratistas.borrar"
                        },
                        new
                        {
                            Id = 13,
                            Area = "Administracion",
                            ModuloId = 2,
                            Nombre = "Ver Catálogo de Permisos",
                            Slug = "admin.permisos.leer"
                        },
                        new
                        {
                            Id = 14,
                            Area = "Administracion",
                            ModuloId = 2,
                            Nombre = "Crear Catálogo de Permisos",
                            Slug = "admin.permisos.crear"
                        },
                        new
                        {
                            Id = 15,
                            Area = "Administracion",
                            ModuloId = 2,
                            Nombre = "Editar Catálogo de Permisos",
                            Slug = "admin.permisos.editar"
                        },
                        new
                        {
                            Id = 16,
                            Area = "Administracion",
                            ModuloId = 2,
                            Nombre = "Eliminar Catálogo de Permisos",
                            Slug = "admin.permisos.borrar"
                        },
                        new
                        {
                            Id = 17,
                            Area = "Proyectos",
                            ModuloId = 3,
                            Nombre = "Ver Energía",
                            Slug = "proyectos.energia.leer"
                        },
                        new
                        {
                            Id = 18,
                            Area = "Proyectos",
                            ModuloId = 3,
                            Nombre = "Crear Energía",
                            Slug = "proyectos.energia.crear"
                        },
                        new
                        {
                            Id = 19,
                            Area = "Proyectos",
                            ModuloId = 3,
                            Nombre = "Editar Energía",
                            Slug = "proyectos.energia.editar"
                        },
                        new
                        {
                            Id = 20,
                            Area = "Proyectos",
                            ModuloId = 3,
                            Nombre = "Eliminar Energía",
                            Slug = "proyectos.energia.borrar"
                        },
                        new
                        {
                            Id = 21,
                            Area = "Proyectos",
                            ModuloId = 3,
                            Nombre = "Ver Obra Civil",
                            Slug = "proyectos.obracivil.leer"
                        },
                        new
                        {
                            Id = 22,
                            Area = "Proyectos",
                            ModuloId = 3,
                            Nombre = "Crear Obra Civil",
                            Slug = "proyectos.obracivil.crear"
                        },
                        new
                        {
                            Id = 23,
                            Area = "Proyectos",
                            ModuloId = 3,
                            Nombre = "Editar Obra Civil",
                            Slug = "proyectos.obracivil.editar"
                        },
                        new
                        {
                            Id = 24,
                            Area = "Proyectos",
                            ModuloId = 3,
                            Nombre = "Eliminar Obra Civil",
                            Slug = "proyectos.obracivil.borrar"
                        },
                        new
                        {
                            Id = 25,
                            Area = "Proyectos",
                            ModuloId = 3,
                            Nombre = "Ver Telecomunicaciones",
                            Slug = "proyectos.telecom.leer"
                        },
                        new
                        {
                            Id = 26,
                            Area = "Proyectos",
                            ModuloId = 3,
                            Nombre = "Crear Telecomunicaciones",
                            Slug = "proyectos.telecom.crear"
                        },
                        new
                        {
                            Id = 27,
                            Area = "Proyectos",
                            ModuloId = 3,
                            Nombre = "Editar Telecomunicaciones",
                            Slug = "proyectos.telecom.editar"
                        },
                        new
                        {
                            Id = 28,
                            Area = "Proyectos",
                            ModuloId = 3,
                            Nombre = "Eliminar Telecomunicaciones",
                            Slug = "proyectos.telecom.borrar"
                        },
                        new
                        {
                            Id = 29,
                            Area = "Finanzas",
                            ModuloId = 4,
                            Nombre = "Ver Finanzas",
                            Slug = "finanzas.leer"
                        },
                        new
                        {
                            Id = 30,
                            Area = "Finanzas",
                            ModuloId = 4,
                            Nombre = "Crear Finanzas",
                            Slug = "finanzas.crear"
                        },
                        new
                        {
                            Id = 31,
                            Area = "Finanzas",
                            ModuloId = 4,
                            Nombre = "Editar Finanzas",
                            Slug = "finanzas.editar"
                        },
                        new
                        {
                            Id = 32,
                            Area = "Finanzas",
                            ModuloId = 4,
                            Nombre = "Eliminar Finanzas",
                            Slug = "finanzas.borrar"
                        },
                        new
                        {
                            Id = 33,
                            Area = "Gestion Humana",
                            ModuloId = 5,
                            Nombre = "Ver Gestión Humana",
                            Slug = "gestionhumana.leer"
                        },
                        new
                        {
                            Id = 34,
                            Area = "Gestion Humana",
                            ModuloId = 5,
                            Nombre = "Crear Gestión Humana",
                            Slug = "gestionhumana.crear"
                        },
                        new
                        {
                            Id = 35,
                            Area = "Gestion Humana",
                            ModuloId = 5,
                            Nombre = "Editar Gestión Humana",
                            Slug = "gestionhumana.editar"
                        },
                        new
                        {
                            Id = 36,
                            Area = "Gestion Humana",
                            ModuloId = 5,
                            Nombre = "Eliminar Gestión Humana",
                            Slug = "gestionhumana.borrar"
                        },
                        new
                        {
                            Id = 37,
                            Area = "SST",
                            ModuloId = 2,
                            Nombre = "Ver SST",
                            Slug = "sst.leer"
                        },
                        new
                        {
                            Id = 38,
                            Area = "SST",
                            ModuloId = 2,
                            Nombre = "Crear SST",
                            Slug = "sst.crear"
                        },
                        new
                        {
                            Id = 39,
                            Area = "SST",
                            ModuloId = 2,
                            Nombre = "Editar SST",
                            Slug = "sst.editar"
                        },
                        new
                        {
                            Id = 40,
                            Area = "SST",
                            ModuloId = 2,
                            Nombre = "Eliminar SST",
                            Slug = "sst.borrar"
                        });
                });

            modelBuilder.Entity("RmsErp.Api.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("RmsErp.Api.Models.UsuarioPermiso", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PermisoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.HasKey("UsuarioId", "PermisoId");

                    b.HasIndex("PermisoId");

                    b.ToTable("UsuarioPermisos");
                });

            modelBuilder.Entity("RmsErp.Api.Models.Permiso", b =>
                {
                    b.HasOne("RmsErp.Api.Models.Modulo", "ModuloRelacion")
                        .WithMany("ListaPermisos")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ModuloRelacion");
                });

            modelBuilder.Entity("RmsErp.Api.Models.UsuarioPermiso", b =>
                {
                    b.HasOne("RmsErp.Api.Models.Permiso", "Permiso")
                        .WithMany("UsuarioPermisos")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RmsErp.Api.Models.Usuario", "Usuario")
                        .WithMany("UsuarioPermisos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RmsErp.Api.Models.Modulo", b =>
                {
                    b.Navigation("ListaPermisos");
                });

            modelBuilder.Entity("RmsErp.Api.Models.Permiso", b =>
                {
                    b.Navigation("UsuarioPermisos");
                });

            modelBuilder.Entity("RmsErp.Api.Models.Usuario", b =>
                {
                    b.Navigation("UsuarioPermisos");
                });
#pragma warning restore 612, 618
        }
    }
}
