// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RmsErp.Api.Data;

#nullable disable

namespace RmsErp.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260322020626_TransformacionSistemaPermisos")]
    partial class TransformacionSistemaPermisos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RmsErp.Api.Models.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactoPrincipal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("RmsErp.Api.Models.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Permisos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = "Administracion",
                            Nombre = "Ver Usuarios",
                            Slug = "admin.usuarios.leer"
                        },
                        new
                        {
                            Id = 2,
                            Area = "Administracion",
                            Nombre = "Crear Usuarios",
                            Slug = "admin.usuarios.crear"
                        },
                        new
                        {
                            Id = 3,
                            Area = "Administracion",
                            Nombre = "Editar Usuarios",
                            Slug = "admin.usuarios.editar"
                        },
                        new
                        {
                            Id = 4,
                            Area = "Administracion",
                            Nombre = "Eliminar Usuarios",
                            Slug = "admin.usuarios.borrar"
                        },
                        new
                        {
                            Id = 5,
                            Area = "Administracion",
                            Nombre = "Ver Clientes",
                            Slug = "admin.clientes.leer"
                        },
                        new
                        {
                            Id = 6,
                            Area = "Administracion",
                            Nombre = "Crear Clientes",
                            Slug = "admin.clientes.crear"
                        },
                        new
                        {
                            Id = 7,
                            Area = "Administracion",
                            Nombre = "Editar Clientes",
                            Slug = "admin.clientes.editar"
                        },
                        new
                        {
                            Id = 8,
                            Area = "Administracion",
                            Nombre = "Eliminar Clientes",
                            Slug = "admin.clientes.borrar"
                        },
                        new
                        {
                            Id = 9,
                            Area = "Administracion",
                            Nombre = "Ver Contratistas",
                            Slug = "admin.contratistas.leer"
                        },
                        new
                        {
                            Id = 10,
                            Area = "Administracion",
                            Nombre = "Crear Contratistas",
                            Slug = "admin.contratistas.crear"
                        },
                        new
                        {
                            Id = 11,
                            Area = "Administracion",
                            Nombre = "Editar Contratistas",
                            Slug = "admin.contratistas.editar"
                        },
                        new
                        {
                            Id = 12,
                            Area = "Administracion",
                            Nombre = "Eliminar Contratistas",
                            Slug = "admin.contratistas.borrar"
                        },
                        new
                        {
                            Id = 13,
                            Area = "Proyectos",
                            Nombre = "Ver Energía",
                            Slug = "proyectos.energia.leer"
                        },
                        new
                        {
                            Id = 14,
                            Area = "Proyectos",
                            Nombre = "Crear Energía",
                            Slug = "proyectos.energia.crear"
                        },
                        new
                        {
                            Id = 15,
                            Area = "Proyectos",
                            Nombre = "Editar Energía",
                            Slug = "proyectos.energia.editar"
                        },
                        new
                        {
                            Id = 16,
                            Area = "Proyectos",
                            Nombre = "Eliminar Energía",
                            Slug = "proyectos.energia.borrar"
                        },
                        new
                        {
                            Id = 17,
                            Area = "Proyectos",
                            Nombre = "Ver Obra Civil",
                            Slug = "proyectos.obracivil.leer"
                        },
                        new
                        {
                            Id = 18,
                            Area = "Proyectos",
                            Nombre = "Crear Obra Civil",
                            Slug = "proyectos.obracivil.crear"
                        },
                        new
                        {
                            Id = 19,
                            Area = "Proyectos",
                            Nombre = "Editar Obra Civil",
                            Slug = "proyectos.obracivil.editar"
                        },
                        new
                        {
                            Id = 20,
                            Area = "Proyectos",
                            Nombre = "Eliminar Obra Civil",
                            Slug = "proyectos.obracivil.borrar"
                        },
                        new
                        {
                            Id = 21,
                            Area = "Proyectos",
                            Nombre = "Ver Telecomunicaciones",
                            Slug = "proyectos.telecom.leer"
                        },
                        new
                        {
                            Id = 22,
                            Area = "Proyectos",
                            Nombre = "Crear Telecomunicaciones",
                            Slug = "proyectos.telecom.crear"
                        },
                        new
                        {
                            Id = 23,
                            Area = "Proyectos",
                            Nombre = "Editar Telecomunicaciones",
                            Slug = "proyectos.telecom.editar"
                        },
                        new
                        {
                            Id = 24,
                            Area = "Proyectos",
                            Nombre = "Eliminar Telecomunicaciones",
                            Slug = "proyectos.telecom.borrar"
                        },
                        new
                        {
                            Id = 25,
                            Area = "Finanzas",
                            Nombre = "Ver Finanzas",
                            Slug = "finanzas.leer"
                        },
                        new
                        {
                            Id = 26,
                            Area = "Finanzas",
                            Nombre = "Crear Finanzas",
                            Slug = "finanzas.crear"
                        },
                        new
                        {
                            Id = 27,
                            Area = "Finanzas",
                            Nombre = "Editar Finanzas",
                            Slug = "finanzas.editar"
                        },
                        new
                        {
                            Id = 28,
                            Area = "Finanzas",
                            Nombre = "Eliminar Finanzas",
                            Slug = "finanzas.borrar"
                        },
                        new
                        {
                            Id = 29,
                            Area = "Gestion Humana",
                            Nombre = "Ver Gestión Humana",
                            Slug = "gestionhumana.leer"
                        },
                        new
                        {
                            Id = 30,
                            Area = "Gestion Humana",
                            Nombre = "Crear Gestión Humana",
                            Slug = "gestionhumana.crear"
                        },
                        new
                        {
                            Id = 31,
                            Area = "Gestion Humana",
                            Nombre = "Editar Gestión Humana",
                            Slug = "gestionhumana.editar"
                        },
                        new
                        {
                            Id = 32,
                            Area = "Gestion Humana",
                            Nombre = "Eliminar Gestión Humana",
                            Slug = "gestionhumana.borrar"
                        },
                        new
                        {
                            Id = 33,
                            Area = "SST",
                            Nombre = "Ver SST",
                            Slug = "sst.leer"
                        },
                        new
                        {
                            Id = 34,
                            Area = "SST",
                            Nombre = "Crear SST",
                            Slug = "sst.crear"
                        },
                        new
                        {
                            Id = 35,
                            Area = "SST",
                            Nombre = "Editar SST",
                            Slug = "sst.editar"
                        },
                        new
                        {
                            Id = 36,
                            Area = "SST",
                            Nombre = "Eliminar SST",
                            Slug = "sst.borrar"
                        });
                });

            modelBuilder.Entity("RmsErp.Api.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("RmsErp.Api.Models.UsuarioPermiso", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PermisoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.HasKey("UsuarioId", "PermisoId");

                    b.HasIndex("PermisoId");

                    b.ToTable("UsuarioPermisos");
                });

            modelBuilder.Entity("RmsErp.Api.Models.UsuarioPermiso", b =>
                {
                    b.HasOne("RmsErp.Api.Models.Permiso", "Permiso")
                        .WithMany("UsuarioPermisos")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RmsErp.Api.Models.Usuario", "Usuario")
                        .WithMany("UsuarioPermisos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RmsErp.Api.Models.Permiso", b =>
                {
                    b.Navigation("UsuarioPermisos");
                });

            modelBuilder.Entity("RmsErp.Api.Models.Usuario", b =>
                {
                    b.Navigation("UsuarioPermisos");
                });
#pragma warning restore 612, 618
        }
    }
}
